spring:
  application:
    name: university
  datasource:
    url: jdbc:mysql://localhost:3306/university
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345
  jpa:
    show-sql: true