package com.company.error;

public enum ErrorCode {

    AUTHOR_NOT_FOUND,
    BOOK_NOT_FOUND,
    EXAM_RESULT_NOT_FOUND,
    FACULTY_NOT_FOUND,
    LESSON_NOT_FOUND,
    QUESTION_NOT_FOUND,
    STUDENT_NOT_FOUND,
    TEACHER_NOT_FOUND,
    THE_COUNT_OF_ANSWERS_IS_INCORRECT

}